name: dbt PR Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  run-dbt:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dbt
        run: |
          pip install dbt-core dbt-sqlserver

      - name: Run dbt compile
        run: |
          dbt compile

      - name: Run the stored procedure
        run: |
           dbt run-operation run_insert_orders

      - name: Run dbt tests
        run: |
          dbt test --select orders_summary
